project_id = "ifdorcgbhxzwktjlxqfo"

[functions.sync-congress-members]
verify_jwt = false

[functions.sync-bills]
verify_jwt = false

[functions.calculate-member-scores]
verify_jwt = false

[functions.sync-votes]
verify_jwt = false
